### ISSUE TITLE
Code in Readme does not reflect the current 

### ISSUE THREAD

**Issue by pmasrani** [vmware/liota#15]
For example, WebSocket(URL "secure") is not valid anymore, vrops.register returns a value, etc.

**Comment by GregBollella** [comment]
Agree. We need to bring the README up to current. THEN, developers responsible for a pull should also make appropriate changes to the README. I.E, README changes must be part of every pull.

**Comment by KohliDev** [comment]
README.md up to date as per the latest refactoring code changes.In future,developers responsible for a pull should make appropriate changes to README. Hence,closing this issue.
