### ISSUE TITLE
/usr/lib/liota is not created with pip install

### ISSUE THREAD

**Issue by carlosprados** [vmware/liota#209]
Hello, I'm starting with Liota and I followed the instructions that appear in the README. The section "**Installation and Testing**" says there are some files under the `/usr/lib/liota` folder, however after a fresh `sudo -H pip install liota` I can not find any `/usr/lib/liota` folder, therefore I can not execute the post install process.

Any idea?

The tests were run on a Ubuntu 16.04 machine.

Thanks in advance.

**Comment by lucifercr07** [comment]
Currently the pip hasn't been updated. Please clone the repository and run setup.py then you will be have the directory  /usr/lib/liota then you can follow steps given in the Readme file [https://github.com/vmware/liota/blob/master/README.md#installation-and-testing]

**Comment by carlosprados** [comment]
Thak you very much, it works following your instructions.

**Comment by KohliDev** [comment]
By next week we'll have the latest PIP build available. Thanks for your patience.
