### ISSUE TITLE
请问是否有中文版本示例与文档？

### ISSUE THREAD

**Issue by gaoyiping** [vmware/liota#220]
目前在国内（中国大陆）没有发现有社区或博客有相关内容。

**Comment by gaoyiping** [comment]
hello???

**Comment by lihaoyucool** [comment]
我是vmware北京做这块开发工作的工程师。liota目前是没有中文文档的，请问为什么要中文文档呢？

**Comment by mrulke** [comment]
He is asking "Is there a Chinese version of the sample and documentation"

**Comment by KohliDev** [comment]
That's not available as of now.

**Comment by gaoyiping** [comment]
okay,thx
