### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by keilw** [vmware/liota#7]
>unit = An SI Unit (work needed here)
Could any of these Python libraries for Unit support be of help?
http://www.drdobbs.com/jvm/quantities-and-units-in-python/240161101

**Comment by GregBollella** [comment]
keilw, 
Great Suggestions! Love it. Will look over the packages in detail but will very likely include one in our install for developers writing apps on liota!!

Thanks Again!

Greg

**Comment by keilw** [comment]
Happy to help. For the Java binding, though it does not seem started yet, https://github.com/unitsofmeasurement may provide similar support (and several solutions in other languages were at least partly inspired by it;-)

**Comment by keilw** [comment]
As for JSR-363 we also use the BSD (3-clause) license, so assuming the Java part was under the same BSD license as the rest of liota it would be perfectly compatible from a license point.

**Comment by KohliRocks** [comment]
Thanks Werner for suggesting the packages. We have added PINT library as part of liota packaging f56e57df001c627eddb7ac8c33ff4816ecc1bc04 ,have also added one small example around temperature conversion using the library, we are working on the more detailed example.

**Comment by keilw** [comment]
Glad to help. I'd love to see the Java part, any idea when that's coming?
