### ISSUE TITLE
Using **kwargs in _connect() of DeviceComms and DccComms

### ISSUE THREAD

**Issue by Venkat2811** [vmware/liota#73]
Data members required for establishing connection in Transport layer are stored in `init()` method of DeviceComms and DccComms, so that `self._connect()` can be called.  This results in duplication.

Why don't we use **kwargs in abstract `_connect()` method, so that it can take dynamic arguments instead ?

**Comment by Venkat2811** [comment]
Hi @bfrggit,

Could you please explain why `self._connect()` should be kept free of external arguments as mentioned in the comment [here](https://github.com/vmware/liota/blob/master/liota/dcc_comms/dcc_comms.py#L45) ? 

If it is to facilitate dynamic number of arguments as each transport requires different arguments, why don't we use `_connect(**kwargs)` instead ?

Adding @KohliDev

**Comment by bfrggit** [comment]
We want to keep the parameters.

At the same time, if we put the parameters in _connect(), it gives the possibility that some one call this method on the same obj multiple times with different parameters, which may cause troubles.

**Comment by Venkat2811** [comment]
Oh okay.  Thanks for explaining.
