### ISSUE TITLE
What is the IoTCC? 

### ISSUE THREAD

**Issue by evileye2000** [vmware/liota#77]
Hi,
I can't find any information about IoTCC.
Can anyone tell me what is IoTCC and project web site or other information.

Thanks.

**Comment by KohliDev** [comment]
IoTCC (IoT Control Centre) 
It is still in development and is VMware`s DCC component used to manage IoT infrastructure. We`ll provide information on the git about it pretty soon.

**Comment by KohliDev** [comment]
Project ICE, IoTCC to be documented.
